# Generated by Django 3.2.4 on 2021-07-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
    ]
