# Generated by Django 3.2.4 on 2021-07-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentApp', '0002_auto_20210703_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
